name: Leewood Chan
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true

exclude:
 - node_modules


sass:
    load_paths:
        - _sass
        - node_modules
